name: build
on: push

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@latest
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@latest
        with:
          java-version: 25
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@latest
        with:
          gradle-version: wrapper

      - name: Cache Gradle packages
        uses: actions/cache@latest
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew buildAndCollect --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@latest
        with:
          name: build-artifacts
          path: build/libs/
